export const SPECIALIZATIONS = [
  'General Practitioner',
  'Family Medicine',
  'Internal Medicine',
  'Pediatrics',
  'OB-GYN',
  'Surgery',
  'Orthopedics',
  'Cardiology',
  'Dermatology',
  'ENT (Ear, Nose & Throat)',
  'Ophthalmology',
  'Neurology',
  'Psychiatry',
  'Pulmonology',
  'Urology',
  'Radiology',
  'Anesthesiology',
  'Rehabilitation Medicine',
  'Oncology',
  'Endocrinology',
  'Nephrology',
  'Gastroenterology',
  'Rheumatology',
  'Infectious Disease',
  'Emergency Medicine',
  'Nursing',
  'Medical Technologist',
  'Physical Therapist',
  'Other',
] as const